name: Deploy Website ke Server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy ke Hosting
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        # --- PERBAIKAN DI SINI ---
        # Tambahkan 'security: false' untuk mengatasi error Control Socket
        security: false
        
        # Pastikan folder tujuan sudah benar (sesuai settingan cPanel Anda)
<<<<<<< HEAD
        server-dir: /public_html/mandiribelajar.my.id/

=======
        server-dir: /public_html/kursus.quizb.my.id/
        
>>>>>>> dce7a683a6b566645d3d761b44022b251a6e27ed
        exclude: |
          **/.git*
          **/.github*
          **/README.md
